sonar.projectKey=revpay-frontend
sonar.projectName=RevPay Angular Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/revpay-frontend/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=squ_c36d2d55bcf621ff8b9a7f074e2dc83b7463d21d
