server.port=8086
spring.application.name=notification-service

# --- DYNAMIC DOCKER NETWORKING ---
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/revpay_notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Vijay@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- DYNAMIC EUREKA NETWORKING ---
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

# --- DYNAMIC CONFIG SERVER NETWORKING ---
spring.config.import=optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}