server.port=8888
spring.application.name=config-server
spring.profiles.active=native

# --- DYNAMIC DOCKER FILE MOUNTING ---
spring.cloud.config.server.native.search-locations=file://${CONFIG_REPO_PATH:${user.home}/Downloads/Er_diagram_of_revpay/sql qc/RevPay-P3/microservices/revpay-config}